version: '3'
services:
  web:
    image: playground
    build: .
    ports:
      - "8142:8080"
    volumes:
      - ./volumes:/volumes
      - ./instance:/instance
    restart: unless-stopped

#pip install --no-cache-dir -r requirements.txt   
#pip install gunicorn 
#e